### ISSUE TITLE
MPI_T: Unique identifiers for MPI_T variables and events

### ISSUE THREAD

**Issue by mahermanns** [mpiwg-tools/tools-issues#12]
# Problem

MPI_T defines the interface to query available performance and config variables. However, the user needs to consult the manual to understand the semantics of a specific variable. Tools can query and store a variable description, but will be unable to compare its semantics to previous versions of this variable or variables of the same name.

# Proposal

Using IEEE company identifiers (CID) as a 24-bit prefix in a larger integer-based variable, an MPI vendor can assign unique IDs to every variable, that a tool can query at runtime. A unique identifier for a variable guarantees that the semantics of this variable does not change in the future. Tool implementors can use the ID to decide on how to process a variable.

# Changes to the Text

The changes will be integrated to the MPI_T section of the Tool Support chapter.

# Impact on Implementations

Implementors providing their own variables will have to register a CID at IEEE (many network vendors already have viable CID values, because IEEE OUI values can also be used as CID values) for $685 USD (as of April 2017). Implementors are free to use the remaining bits of the identifiers (following their own CID) as they see fit to identify a variable uniquely. Implementors are allowed to use the unique identifiers outside of their own prefix for a variable, if that variable follows the same semantics as specified by the owner of the ID.

# Impact on Users

Tool implementors will be able to identify variables that are portable across multiple MPI implementations. For example, a vendor-provided MPI implementation derived from an open source MPI implementation may chose to provide some of the variables of its origin potentially under a different name. If the implementation chooses to change the semantics in a future version, they can keep the same name, but only have to change the unique ID and a tool can easily detect the semantic change (and issue a warning or proceed otherwise).

# References

* IEEE CID Registration Authority:
  http://standards.ieee.org/develop/regauth/cid/

**Comment by jsquyres** [comment]
@mahermanns I'm a bit confused by the statement "Implementors do ***not*** need to provide a unique identifier for each variable" (emphasis added by me).  Why wouldn't we *require* unique IDs?

**Comment by mahermanns** [comment]
@jsquyres Yes. As we discussed in the last meeting, the interface would be of more use, if the unique IDs were required for every implementor-provided variable. I changed the text accordingly.

**Comment by jsquyres** [comment]
Per https://github.com/mpi-forum/mpi-issues/issues/113#issuecomment-442610133, we'll talk about this further.  Some data points and links for further reading:

* IEEE OUI's and CID's are 24 bit values.
* OUIs and CIDs are effectively in different namespaces -- there's a specific bit==0 in OUIs and bit==1 in CIDs.  Because of this, MPI can (should) actually allow *both* OUIs *and* CIDs (e.g., Cisco has many OUIs, but no CIDs).
* CIDs were formally created / split off from OUIs on Jan 1, 2014 to reduce the consumption of OUIs (because OUIs are used in Ethernet MAC addresses, but CIDs are not)
* CIDs now apparently cost $705 (Nov 2018).
* https://en.wikipedia.org/wiki/Organizationally_unique_identifier Wikipedia article on IEEE OUIs; CIDs are also mentioned on this page.
* https://standards.ieee.org/products-services/regauth/cid/index.html (@mahermanns cited this one above, but I'm putting it here, just to be complete) Basic definitions for an IEEE CID 
* https://standards.ieee.org/content/dam/ieee-standards/standards/web/documents/tutorials/eui.pdf "Guidelines for Use of Organizationally Unique Identifiers (OUI) and Company ID (CID)"
* Listing of all existing CIDs: http://standards-oui.ieee.org/cid/cid.txt and http://standards-oui.ieee.org/cid/cid.csv
* Listing of all existing OUIs: http://standards-oui.ieee.org/oui/oui.txt and http://standards-oui.ieee.org/oui/oui.csv

Fun facts:

* As you would expect, Cisco, Intel, Mellanox, IBM, Fujitsu, HP, Cray, NEC, NVIDIA, Microsoft all have OUIs.
* ETH Zurich has an OUI
* UC Berkeley has an OUI
* U Tokyo has an OUI
* Kyoto U has an OUI
* U Oaklahoma has an OUI
* The Missouri Department of Transportation has an OUI

**Comment by jsquyres** [comment]
Per discussion on the Tools WG call today, the tentative plan is:

* Use OUIs/CIDs as the 24 bit organization identifier.
* Do not write a side document, but rather write a few paragraphs in the MPI spec about UIDs and how the org ID is an IEEE OUI/CID, ...etc.
* The MPI Forum will buy a CID.
    * The Forum therefore dictates the format of the remaining 40 bits.
    * If the MSB of that 40 bits is 0, it represents a UID that has a standardized meaning in the MPI specification.
    * If the MSB of that 40 bits is 1, it represents a UID that is unstandardized and is available for general use (e.g., by students and independant researchers).  It is very analogous to `MPIX_`-prefixed symbols.

I was charged with finding 3 things:

1. Can an open source software group (e.g., Open MPI) buy a CID?
    * It looks like I asked exactly this question back in Feb 2017 when we first approached this idea, and I emailed IEEE to ask.  After a bunch of back and forths, the answer is **yes**, and open source organization (e.g., Open MPI) that has no legal entity can purchase a CID.
1. What are the relevant IEEE standards to cite for OUIs?
    * IEEE 802®-2001
1. What are the relevant IEEE standards to cite for CIDs?
    * IEEE 1212™-1991
    * IEEE 896.2™-1991

**Comment by kathrynmohror** [comment]
@jsquyres Are you certain on the citations for CIDs? I don't read IEEE specs ever so I could be missing something but the titles don't give me confidence that they are related to CID:
https://standards.ieee.org/standard/1212-1991.html
https://standards.ieee.org/standard/896_2-1991.html

The OUI one looks legit: https://standards.ieee.org/standard/802-2001.html

**Comment by jsquyres** [comment]
Those are the ones cited in https://standards.ieee.org/products-services/regauth/cid/index.html.

> The 'company_id' relevant standards as defined in IEEE 1212™-1991 Control and Status Register (CSR) Architecture referenced by IEEE 896.2™-1991 Futurebus+Physical Layers and Profiles include: ...

**Comment by kathrynmohror** [comment]
Works for me. Thanks for confirming!

**Comment by mahermanns** [comment]
Closing the ticket in favor of the MPI Forum ticket at https://github.com/mpi-forum/mpi-issues/issues/113

Any further discussion will be held on that ticket.
