### ISSUE TITLE
MPI_T: MPI_Init vs MPI_Init_thread

### ISSUE THREAD

**Issue by kathrynmohror** [mpiwg-tools/tools-issues#9]
In some places in the MPI_T chapter, we use MPI_Init and in others we use MPI_Init_thread. We need to go through the chapter/relevant section and check for consistency on this.

**Comment by mahermanns** [comment]
As discussed in our call on May 11, 2017, we agreed on referencing MPI's state of initialization rather than specific calls to MPI_INIT or MPI_INIT_THREAD. Depending on the acceptance of another ticket to clarify and define the state of MPI being initialized. I prepared an annotated [PDF](https://github.com/mpiwg-tools/tools-issues/files/996050/mpi31-report-t-issue-9-annotated.pdf) marking the passages that would need changes. Please check if this represents our state of discussion.
